### ISSUE TITLE
USER STORY: View Place Details

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#10]
## EPIC: #7 

As a **Site User** I can **view details of a specific place** so that **I can decide whether I should add it to my itinerary**

## Acceptance Criteria

* Clicking on a place either on the recommendations page or in the user's trip itinerary should present the user with an expanded details view of that specific place
* If the place has been visited by other site members, the user should be able to browse related reviews
* The user should have the ability to leave their own review once they have visited the place

## Tasks

* [x] Create 'place_detail' function based view that takes place_id as an argument, alongside the trip_id
* [x] Obtain a queryset from the database of all reviews belonging to the place (specified by place_id)
* [x] When rendering the 'place_detail.html' template, pass the trip object, place object, reviews queryset and ReviewForm to the template
* [x] Add url pattern with the name 'place_detail'
* [x] Add links to the 'place_detail' url pattern in the 'trip_recommendations.html' and 'trip_detail.html' templates
* [x] Access and display attributes of 'place' and 'trip' to the user in the 'place_detail.html' template
* [x] Use a for loop to iterate over 'reviews' and display to user in the 'place_detail.html' template

**Comment by rkillickdev** [comment]
Acceptance Criteria 3 - ability to leave reviews and upload images for a place has been implemented by adding navigation links to these pages in the itinerary accordion on the trip detail page.  I felt this offered better user experience rather than locating these links on the place detail page.
