### ISSUE TITLE
USER STORY: Add Place to Trip

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#11]
## EPIC: #7 

As a **Site User** I can **add a recommendation to my trip planner** so that **I can build an itinerary to use and refer to when travelling to the location**

## Acceptance Criteria

* Clicking on the 'Add' icon positioned next to each place should allow the user to add it to their trip itinerary
* A tally of the number of places added to the trip itinerary should be displayed on the trip recommendations page
* A list of places added to the trip should be displayed on the trip_detail page.
* Once the place has been added to the trip itinerary, the add icon should change to a subtract icon

## Tasks

* [x] Create PlaceAdd function that contains a 'post' method which takes trip_id and place_id as arguments.
* [x] Arguments are used to obtain specific trip and place from database
* [x] If the place already belongs to trip.places, it is removed and if not it is added
* [x] The 'post' function renders the 'trip_recommendations' page
* [x] Create a form to be included in the trip_recommendation.html template.  The method should be 'POST' and the action should point at the 'add_place' url with trip.id and place.id provided as arguments
* [x] Use the number_of_places() method defined in the Trip model, to display the number of places added to the trip on the trip_recommendations template

**Comment by rkillickdev** [comment]
The final acceptance criteria of changing an icon dependent on whether a place belongs to trip.places, will be addressed as part of styling in a later sprint

**Comment by rkillickdev** [comment]
Acceptance Criteria 2 - I deemed it unnecessary in the end to display a tally of places added to a trip.
