### ISSUE TITLE
USER STORY: View Trips

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#17]
## EPIC: #16 

As a **Site User** I can **view  a summary of all upcoming and completed trips** so that **I can choose one to view or edit**

## Acceptance Criteria

* The user should have the ability to see the title and image for each trip associated with their account
* Upcoming trips should be listed first followed by completed trips in date order
* Clicking on the trip takes the user to a trip detail page where they can see details of their trip, including any places added to their itinerary

## Tasks

* [x] Create TripListView using generic ListView
* [x] Define the context_object_name in the Trip model as 'trip_list'
* [x] Filter the queryset returned by the model so only trips relating to the profile of the logged in user are displayed
* [x] Apply the LoginRequiredMixin to this view to ensure only logged in users can access this page
* [x] Create trip_list.html template and iterate over the 'trip_list' object with a for loop to list each trip belonging to the logged in user.
* [x] Add url pattern for 'trip_list'. 
* [x] Add link to each trip listed in template, that directs user to the 'trip_detail' url for that particular trip.  Pass in trip.slug and trip.id as arguments

**Comment by rkillickdev** [comment]
For acceptance criteria 2, this is something that will be implemented once start and end date functionality is added to trip creation.
