### ISSUE TITLE
USER STORY: View Trip Summary

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#18]
## EPIC: #16 

As a **Site User** I can **select a specific trip** so that **I can view or edit details of the itinerary**

## Acceptance Criteria

* The detail page for each trip should show key details of the trip such as dates, title, description, as stored in the trip object.
* When users create a new trip, they should be directed to this trip_detail page.
* A link should be available for users to click and start browsing recommended places to visit based on the location of the trip.
* Any places that have already been added to the trip should be listed as part of the itinerary on the trip detail page
* An 'edit' button should be available that takes the user to a form where they can edit and update details of their trip

## Tasks

* [x] Create TripDetailView
* [x] Define a method called 'get' which obtains a queryset containing only trips relating to the logged in user from the Trip database.
* [x] The 'get' method should take the trip.id as an argument, supplied by the url.  This id is used to obtain a specific trip object which is then included in the context when the trip_detail.html template is rendered.
* [x] Create trip_detail.html template and a url pattern that looks for the trip slug (for visual purposes - it does not use this to look the trip up), and also the trip id.
* [x] Create TripUpdateView using generic UpdateView.  The success url for this view should redirect the user back to the detail view of the trip they have just updated.  Define trip.slug and trip.id as kwargs that the trip_detail url pattern is expecting.
* [x] Add link to trip_detail page that directs user to the trip_update page
