### ISSUE TITLE
USER STORY: New User Registration

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#2]
## EPIC: #1 

As a **Site User** I can **register an account** so that **I can access features only available to registered users such as creating and planning trips**

## Acceptance Criteria

* Navigating to the site base url/accounts/signup should direct the user to a sign up page
* Once the user submits their details, a new account should be created
* Feedback should be presented to the user if any of the form fields are filled out incorrectly to assist them with signing up
* On successful signup, the site user should be redirected to create profile page

## Tasks

* [x] Add `ACCOUNT_EMAIL_VERIFICATION = 'none'` to settings.py file
* [x] Install django-allauth
* [x] Update requirements.txt file
* [x] Add all auth urls to main urls.py file
* [x] Add all auth apps to `INSTALLED APPS` in settings.py file
* [x] Set `SITE ID = 1` in settings.py file
* [x] Set Login and Logout redirect URLs in settings.py file
* [x] Run Migrations
