### ISSUE TITLE
USER STORY: Delete Trip

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#20]
## EPIC: #16 

As a **Site User** I can **delete an entire trip** so that **I have control of the trips that are stored in my user account**

## Acceptance Criteria

* There should a 'delete' trip button on the trip summary page
* On clicking the 'delete' button, the user should be presented with a message to confirm that they want to delete their trip
* Once the delete request has been submitted, the user should be redirected to an updated 'view trips' page

## Tasks

* [x] Write PlaceRemove view for trips/views.py file
* [x] Add url pattern with the name "remove_place"
* [x] Use HTTP Response Redirect to direct the user to the trip_detail.html template upon successful deletion
* [x] Include the delete confirm modal in the trip_detail.html template
* [x] Add a clickable link on the trip_detail that triggers the delete confirm modal. 
* [x] Use the font awesome trash can icon to indicate the functionality of the clickable link.
* [x] Confirming deletion from the modal should trigger the PlaceRemove view.
