### ISSUE TITLE
USER STORY: Delete Review

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#24]
## EPIC: #21 

As a **Site User** I can **delete my review** so that **I can have control of reviews if I decide they are no longer relevant or necessary**

## Acceptance Criteria

* The user should have the ability to delete one of their own reviews if they are logged in by clicking a 'delete' button beside the review
* The user should be presented with a warning message to check that they want to proceed with deleting their review

## Tasks

* [x] Create 'review_delete' function based view which takes review_id as an argument and gets this instance of review from the database.
* [x] Add defensive programming so a review object can only be deleted if the profile field of the review matches the profile of the logged in user.
* [x] Create url pattern for 'delete_review'
* [x] Add a 'delete' button to the template to appear next to the 'edit' button.  Only displayed for reviews that belong to the logged in user.
* [x] Write JavaScript to display a warning modal if the delete button is clicked and check if the user really wants to delete the review.
* [x] The JavaScript should dynamically set the 'href' attribute for the delete button, so the correct review_id is passed into the 'review_delete' view on the backend.
