### ISSUE TITLE
USER STORY: Add Images

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#26]
## EPIC: #21 

As a **Site User** I can **upload images for a place on my itinerary** so that **I can store the memories from my trip and share these experiences with other site users**

## Acceptance Criteria

* The user should have the ability to upload images for a place, while they are leaving a review
* All uploaded images must be modified and approved by a site administrator before they are available for other site users to view
* When looking at the details of a place, users should be able to see pictures uploaded by other users once they have been approved

## Tasks

* [x] Use a class based CreateView to render image upload form to template
* [x] Overwrite form_valid method, so profile and place fields are automatically populated when the form is submitted, before the new instance of Image is saved to the database.
* [x] Define the approve_images method in the admin file, so administrators can approve images from the django admin panel.
* [x] In order to display images on the same page that they have been uploaded from, define the method get_context_data() and pass the queryset 'images' and the object 'place' into the context, so this can be accessed in the template
