### ISSUE TITLE
USER STORY: Landing Page

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#29]
## EPIC: #28 

As a **Site User** I can **immediately understand the purpose of the site when I arrive at the home page** so that **I can quickly and intuitively start planning trips**

## Acceptance Criteria

* When landing on the home page, the user should immediately be presented with information about the goals of the site
* When landing on the home page, all site users should be given the option to start browsing and gaining inspiration for a trip
* When landing on the home page, all site users should be presented with a call to action to 'start planning'
* If already logged in, when clicking on the 'start planning' link, the user will be directed to their 'trip list' page
* If the site user is not logged in, when clicking on the 'start planning' link the user will be directed to the login page where they can enter login details or follow a link to the signup page.

## Tasks

* [x] Create index.html which extends base.html
* [x] Create a header element which contains a hero image to immediately communicate site goals
* [x] Create a call to action 'start planning' anchor tag within the header which directs the site user to their trip list page.
* [x] Create 3 cards with font awesome icons and brief descriptions outlining core goals of the site.
* [x] Use the Bootstrap 5 Carousel component to display information about destination options for trip planning.
* [x] Use the LoginRequiredMixin for the TripListView.  This will ensure that only authenticated users can gain access to the trip list page, otherwise they will be redirected appropriately to the login.html page.
