### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#30]
## EPIC: #28 

As a **Site User** I can **intuitively navigate the site** so that **I can view the content I require with minimal steps**

## Acceptance Criteria

* If the site user is not logged in, Login and Signup links should appear in the nav bar
* If the site user is logged in, a logout link should appear in the nav bar.
* The navigation links should collapse to a hamburger menu on smaller mobile devices
* The Navbar should appear on every page and be styled consistently

## Tasks

* [x] Create a responsive Navbar with the Bootstrap 5 Navbar component in a separate navbar.html file
* [x] Include the navbar.html file in the base.html so it automatically appears at the top of every page
* [x] Use Django templating 'if/ else' statements to display certain links dependent on whether the user is authenticated or has staff permissions
* [x] Test responsiveness of the Navbar on Google Dev Tools and a variety of mobile devices for the deployed site, to ensure there is a switch to the hamburger menu at the desired screen width.
