### ISSUE TITLE
USER STORY: Site Structure

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#31]
## EPIC: #28 

As a **Site User** I can **view site content simply and intuitively** so that **I can easily gather the information I need**

## Acceptance Criteria

* The layout of the site should be minimal with all information easily accessible
* The layout of each page should be consistent and feel familiar to the user

## Tasks

* [x] Create HTML Templates with core structure and layout for each site page
* [x] Extend templates from base.html
* [x] Apply basic styling common with the rest of the site
* [x] Setup anchor links within templates for intuitive navigation
* [x] Add URL patterns and ensure corresponding views are rendering the correct template

**Comment by rkillickdev** [comment]
This user story is constantly evolving, but at this point templates are set up so users can navigate the site and the flow between pages is as required.  Features may be added as part of new user stories, to improve the user experience and continue improving the overall style of the site.
