### ISSUE TITLE
USER STORY: Site Aesthetic

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#32]
## EPIC: #28 

As a **Site User** I **feel a positive emotional response while interacting with the site** so **I am engaged and continue to use and return**

## Acceptance Criteria

* Styling should be consistent across the site with common themes returning across all pages
* Bootstrap themes should be modified and personalised to give the site it's own feel
* Content should be displayed efficiently with clever design to reduce the number of pages a site user must navigate through to access the information they require
* Images should be used to convey the idea of global travel and inspire the user to plan their own trips

## Tasks

* [x] Setup SASS using Node Package Manger to customise Bootstrap themes
* [x] Create my own style sheet for additional css styling
* [x] Link to Bootstrap JavaScript file via CDN
* [x] Link to FontAwesome JS file via CDN
* [x] Use Bootstrap components as a starting point for displaying content
* [x] Select a variety of decorative images from Pexels.com to use throughout the site
