### ISSUE TITLE
USER STORY: Responsive Design

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#33]
## EPIC: #28 

As a **Site User** I can **view the site on a range of screen sizes** so that **I can enjoy good user experience on my device of choice**

## Acceptance Criteria

* Site content should be displayed in an appropriate format to suit differing screen sizes for a range of devices
* The site should be built with a mobile first approach.  Additional decorative elements may be added to the page on devices where greater screen real estate is available

## Tasks

* [x] Use the Bootstrap 5 grid system based around containers, rows and columns to create a responsive layout
* [x] Use Media Queries to adapt css styling for certain page elements above or below particular screen widths
* [x] Test responsiveness in Google Dev Tools and on a range of devices
