### ISSUE TITLE
USER STORY: Trip Itinerary and Places plotted on Maps

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#38]
## EPIC: #7 

As a **user** I can **see places visually on a map** so that **I can see where they are and plan a route**

## Acceptance Criteria

* Place detail Page shows the location of a place on a map
* Trip Summary page plots places that have been added to the itinerary to a map

## Tasks

* [x] Consult Google Maps documentation
* [x] Get Google Maps API key
* [x] Set limits on Google Maps key usage
* [x] Store API key in env.py file for development and Heroku environment variables for production
* [x] Retrieve google maps key in view and pass to template as part of the context
* [x] For TripDetailView, long/ lat data for each place in the trip should be stored in a geo_list and sent to the template as part of the context.
* [x] Pass maps key and longitude/ latitude data from html template to javascript files securely using the json script template tag
* [x] Set up JavaScript files as per documentation, for single map marker and marker clusters
