### ISSUE TITLE
USER STORY: Staff Login Add Destination

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#39]
## EPIC: #1 

As a **user with staff status** I can **add and amend details for destinations** so that **the content on the site can continually be expanded and updated**

## Acceptance Criteria

* A logged in staff user should be able to access a destination creation/ update form to input details for destinations
* This page should not be available to regular site users
* Once details have been entered, the staff user should be able to review how the destination information will appear to regular site users
* Newly added destinations should appear in the destinations carousel on the home page for all site users (only if this destination has places associated with it and it has been approved by the superuser)

## Tasks

* [x] Create a list view that displays destinations and also the form to create a new destination
* [x] Create url patterns for 'locations' and 'update_destination"
* [x] Use LoginRequiredMixin on class based views
* [x] Create destinations.html template
* [x] Create destinations carousel for home page using Bootstrap component
