### ISSUE TITLE
USER STORY: Admin Login Retrieve Destination Places 

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#40]
## EPIC: #1 

As a **user with staff status** I can **add places for a destination to the database** so that **site users can browse these recommended places and add to their trips**

## Acceptance Criteria

* Once a destination has been created, the staff user should be able to retrieve places for that destination and add to the database
* They should be able to select a location and check to see if any place data exists in the form of a json file.  These json files will have been scraped from the APIFY Trip Advisor Web Scraper tool.
* If data is available, this should be filtered to ensure required fields are present and then saved to the database
* If no data is available, a message should be sent from the Django backend and displayed to the staff user using a toast alert.
* These places should then be available as recommendations to regular site users

## Tasks

* [x] Use APIFY Trip Advisor web scraper to retrieve 100 places for a specified location
* [x] Save APIFY response as a json file and store in /static/data folder
* [x] Modify get_places view (Trips/views.py) so it now searches for and retrieves a json file for the specified location rather than calling the APIFY web scraper API
* [x] If no json data exists for the specified location, send a message to the template from Django
* [x] Create a place_list html template that displays places for a location as a list that can be browsed by unauthenticated site users
* [x] Display these retrieved places on the trip detail page as recommendations for authenticated users
