### ISSUE TITLE
USER STORY: View Star Rating

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#41]
## EPIC: #7 

As a **user** I can **view place ratings displayed as stars** so that **I can immediately understand the popularity of a place**

## Acceptance Criteria

* The rating attribute for each place should be displayed as stars on the 'place detail' page
* The display should use half stars for greater accuracy

## Tasks

* [x] Amend rating in Place Model to a float field and migrate changes
* [x] Write JavaScript that translates place rating float number to display font awesome full stars, half stars and empty stars.
* [x] Display star rating icons in place detail template
