### ISSUE TITLE
BUG: Broken external image links not handled

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#45]
## EPIC: #43 

* If Image links that are loaded from external sources such as the https://media-cdn.tripadvisor.com/ or Cloudinary are broken/ return an error, there is currently no defensive programming in place to ensure a replacement image is displayed

## Acceptance Criteria to resolve bug

* Any image that returns an error should be replaced with a suitable replacement which is located in the static/images directory.

## Tasks

* [x] Write javascript that adds event listeners to image files that have a src attribute referencing an external link
* [x] Listen for an error, and when this occurs, replace the src attribute with a trusted image path to a replacement image
* [x] Use ```e.onerror = null;``` to avoid an infinite loop if the replacement image cannot be found or link is broken
