### ISSUE TITLE
USER STORY: Site Footer

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#46]
## EPIC: #28 

As a **user** I can **access links to social media accounts related to the site** so that **I can find out more about the site and its developer**

## Acceptance Criteria

* The site footer must have clickable icon links for facebook, twitter and instagram that open in separate browser tabs
* The site footer must display details of the developer and a clickable icon link to their github repo that opens in a separate browser tab

## Tasks

* [x] Create footer.html file that is included in the base.html
* [x] Ensure margin-top auto is used on the footer, so it is always pushed to the bottom of the page
* [x] Use font awesome icons to communicate the purpose of each link
* [x] apply link-transform on hover to each link to maintain consistency of UX throughout the site
