### ISSUE TITLE
BUG: Profile Form Submit Button

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#47]
## EPIC: #43 

* Profile form submit button still displays 'Create Profile' if user is updating their profile

## Acceptance Criteria to resolve bug

* When a user is updating their profile details, the form submit button should display 'Update Details'

## Tasks

* [x] Add a form_status attribute to the form container which is either set as "create" or "update".  Use Django templating statements to check if the user is creating a new profile or updating and set form_status attribute accordingly.
* [x] Write javascript to identify the form_status on Dom ContentLoaded
* [x] Use an if statement in the javascript file, to set the value of the profile form submit button to "Update Profile" when the form status is equal to 'update'
