### ISSUE TITLE
PERFORMANCE: Links Not Crawlable

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#48]
## EPIC: #43

* When testing with Lighthouse, I got a Google best practice warning that links on the page were not crawlable  as they did not have an href attribute.  These were anchor tags being used to wrap cards and make them clickable and controlled bootstrap modals.

## Acceptance Criteria

* Ensure this warning does not appear for any pages on the site. Find alternative solution for any anchor tags without an href.

## Tasks

* [x] Replace anchor tags without hrefs with buttons
* [x] Set button with class of border-0 so the button is not visible in any way
* [x] Ensure that the hand pointer tool becomes active over these cards on hover
