### ISSUE TITLE
BUG: Google Maps Markers

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#49]
## EPIC: #43 

* Google maps markers not displaying the correct place names on hover/ clicking.  This is especially bad for user experience when viewing the trip detail map which could be populated with many different markers.  Users want to be able to see how places relate to each other on the map.

## Acceptance Criteria

* Each marker on the map should have  a title with the place it represents.

## Tasks

* [x] Pass place names to javascript files from place detail html template / trip detail template using json_script template tag
* [x] Parse json data and save as variables in javascript file
* [x] Use variables to populate title / info window field
