### ISSUE TITLE
BUG: Trip creation location choices may not have places associated

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#58]
## EPIC: #43

* Staff users are able to create a new location, but may not always add places for this immediately.  These newly created locations currently still appear as a choice when regular site users navigate to the 'create a trip' page, and click the form drop down menu to select a location.

## Acceptance Criteria

* Only locations that have places associated with them should appear as a choice of location when regular site users are creating trips.

## Tasks

* [x] Add an 'approved' boolean field to the Location Model which only a superuser can access and approve.  Set ```default=False```
* [x] Filter the 'location' field queryset in TripForm (trips/forms.py), so only approved locations are returned
* [x] Define an approve_locations method for the class LocationAdmin (locations/ admin.py) so admin users can approve a location in the Django admin panel
* [x] Migrate changes to production database
