### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#6]
## EPIC: #1 

As a **Site User** I can **create and update a user profile for my account** so that **I can personalise my details with a screen name, image and bio**

## Acceptance Criteria

* When a user creates a new account, a profile should automatically be created which is linked to their user account
* When a user is logged in a 'My Profile' link should appear in the nav bar
* When a user successfully creates an account, they should be redirected to a page where they are notified of their successful account and given the opportunity to create a personalised profile by following the 'create profile' link.
* The user should also be presented with a link to 'start planning a trip' if they decide not to fill out this information immediately.
* If the user has not entered any information for their profile page, clicking on the 'My Profile' link in the nav bar will take them directly to the form where they can submit details.
* If the user already has entered profile details, clicking on the 'My Profile' link in the nav bar will take them to their profile page.  They should have the ability to update their details by clicking on an 'edit' button.

## Tasks

* [x] Create Profile model
* [x] Make Migrations
* [x] Register Profile model in admin.py file
* [x] Use signals in Django to automatically create a profile when a new user creates an account
* [x] Create a class based UpdateView in views.py file
* [x] Install django-crispy-forms
* [x] Set up crispy_forms FormHelper in the ProfileForm in forms.py
* [x] Create profile_form.html template to render the form
* [x] Create base.html, nav.html and footer html to create simple page structure
* [x] Create basic index.html and setup views and urls
* [x] Add My Profile link in nav bar for logged in users
* [x] Set href on My Profile link to 'update_profile' url and also pass in the primary key for the logged in user's profile
* [x] Create view, url and template for the profile_register page
* [x] Create link on profile_register.html that directs logged in user to ProfileUpdateView where they can update information.

**Comment by rkillickdev** [comment]
Acceptance criteria 4 omitted, as I decided it would be better not to give a user the choice to skip filling in required profile details
