### ISSUE TITLE
USER STORY: Admin Approve Places

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#61]
## EPIC: #1 

As a **staff user** I can **moderate places through the site interface** so that **I can ensure places with sufficient quality info are displayed to site users**

## Acceptance Criteria

* Once the staff user has added places for a location, when they browse each place detail page, they should have access to a toggle button/icon to 'unapprove' or 'approve' this place.

## Tasks

* [x] Create place_staff_approve_toggle.html template to include in place summary template.  Only display if logged in user is staff.
* [x] Create PlaceApproveToggle view (places/views.py).  Define post and get methods within this.  Post method checks value of the 'approved' field and toggles, then saves to database.  Redirects to 'place_detail' page.
* [x] Add URL called place_toggle_approval
