### ISSUE TITLE
BUG: Page hangs for upload of images with large file size

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#64]
## EPIC: #43

* I was finding that when selecting  larger sized images, submitting the form would cause the page to hang, which was not ideal for UX as nothing was communicated to the user during this delay.

## Acceptance Criteria

* Limit the file size that can be uploaded by the user
* Display a warning to the user if they attempt to upload an image that exceed the maximum file size permitted

## Tasks

* [x] Use javascript to listen for a click event on the 'submit-button'
* [x] Click event on the 'submit-button' triggers a function that checks file size against a predefined maxSizeInBytes variable
* [x] If file size greater than maxSizeInBytes variable, prevent the default 'submit' action and trigger a warning modal
* [x] Create a separate file_warning_modal.html template to be included in the base.html template

**Comment by rkillickdev** [comment]
I discussed this issue with my mentor and decided  limiting file size upload on the form would be better for UX than adding a page loading spinner.
