### ISSUE TITLE
USER STORY: Create Trip

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#8]
## EPIC: #7 

As a **Site User** I can **create a personalised trip planner for a chosen destination** so that **I can start planning places to visit on my trip**

## Acceptance Criteria

* When the user is logged in, on the 'My Trips' page they should be presented with the new trip creation form when Clicking on 'Create Trip'
* The user should be given the option of inputting a name for the trip, an optional description and and optional image
* The user should be given the option to enter start and end dates for the trip
* The user should have the ability to select a trip destination from a drop down menu
* The user should be redirected to a list of recommended places to visit on their trip once they have clicked 'create'

## Tasks

* [x] Create Location and Trip models
* [x] Make Migrations
* [x] Register Location and Trip models in admin.py file
* [x] Add an instance of Location to the database via admin superuser login for testing
* [x] Create TripCreateView class using generic class based views 
* [x] Set up crispy_forms FormHelper in the TripForm in forms.py
* [x] Create trip_form.html template to render the form
* [x] Create form_valid method in TripCreateView class that populates the profile field of Trip with the profile linked to the currently logged in user
* [x] Override save() method for Trip Model and use slugify to automatically populate the slug field with a 'slugified' version of the 'title' field
* [x] Set the success url for TripCreateView to reverse_lazy('trip_recommendations').  Obtain the slug field and id of the created instance of trip using self.object. Assign these as kwargs to pass into the URL.

**Comment by rkillickdev** [comment]
I omitted acceptance criteria 3  (add start and end dates for trip) due to time constraints.  I decided this could be implemented at a later date as a future feature
