### ISSUE TITLE
USER STORY: View Recommended Places

### ISSUE THREAD

**Issue by rkillickdev** [rkillickdev/plan-it-go#9]
## EPIC: #7 

As a **Site User** I can **view recommended activities for the chosen location** so that **I can plan a bespoke itinerary for the trip that appeals to my tastes and interests**

## Acceptance Criteria

* The user should be able to view a list of recommended places to visit based on their trip destination on a trip_recommendations page.

## Tasks

* [x] Store APIFY Trip Advisor Web Scraper API keys in env.py file
* [x] Create Places app in Django
* [x] Create Place model with fields that map to APIFY web scraper JSON response
* [x] Register Place model in admin.py file
* [x] Make migrations and migrate to database
* [x] Create an html template including a form to select a location to use in the APIFY Trip Advisor API request (only accessible to site administrators)
* [x] Write a function based view that implements the following in order to populate the Places Database:
   * [x] Takes the location submitted on the form and stores this as the variable 'requested_location'
   * [x] Pass 'requested_location' as an argument to APIFY API call 
   * [x] Map data from API response to fields in the Place model
   * [x] For each place in the API dataset, create an instance of Place, populate fields with data retrieved from the API call, and save the instance to the database
   * [x] Do not save the instance if the venue_id for the place already exists
   * [x] Once places have been saved in the database, make these available as part of the context dictionary so they can be rendered as a list below the form on the html page
* [x] Write a TripRecommendationsView and within this define a get() method that takes in the slug and id as arguments and preforms the following functionality:
   * [x] A queryset should initially be created using filter so only trips belonging to the profile of the currently logged in user can be accessed. 
   * [x] The get_object_or_404() method should then be used on the queryset of trips.  The id passed in the URL is used to look up the specific trip object.  
   * [x] The trip.location can then be used to filter a queryset of places relating to this location.  'places' is returned at part of the context when rendering the trip_recommendations.html template
* [x] Create trip_recommendations.html template and iterate over the 'places' queryset to provide a list of places relevant to the location of the trip
* [x] Create url pattern for trip_recommendations which looks for trip.slug and trip.id
